[package]
name = "authtoken"
version = "0.2.0"
authors = ["Matthew Bentley <matthew.t.bentley@gmail.com>"]

[dependencies]
rust-crypto = "0.2.34"
time = "0.1.34"
hyper = "0.6.16"
rustc-serialize = "0.3.18"
cookie = "0.1.21"
