[package]
name = "authtoken"
version = "0.2.1"
authors = ["Matthew Bentley <matthew.t.bentley@gmail.com>"]

[dependencies]
rust-crypto = "^0.2"
time = "^0.1"
hyper = "^0.6"
rustc-serialize = "^0.3"
cookie = "^0.1"
